package com.example.yummyapp.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF775A00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDF97)
val md_theme_light_onPrimaryContainer = Color(0xFF251A00)
val md_theme_light_secondary = Color(0xFF825500)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDDB2)
val md_theme_light_onSecondaryContainer = Color(0xFF291800)
val md_theme_light_tertiary = Color(0xFF944B00)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDCC5)
val md_theme_light_onTertiaryContainer = Color(0xFF301400)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF410005)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF410005)
val md_theme_light_surfaceVariant = Color(0xFFECE1CF)
val md_theme_light_onSurfaceVariant = Color(0xFF4D4639)
val md_theme_light_outline = Color(0xFF7E7667)
val md_theme_light_inverseOnSurface = Color(0xFFFFEDEB)
val md_theme_light_inverseSurface = Color(0xFF5F1416)
val md_theme_light_inversePrimary = Color(0xFFEFC048)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF775A00)
val md_theme_light_outlineVariant = Color(0xFFD0C5B4)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFEFC048)
val md_theme_dark_onPrimary = Color(0xFF3E2E00)
val md_theme_dark_primaryContainer = Color(0xFF5A4400)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDF97)
val md_theme_dark_secondary = Color(0xFFFFB94E)
val md_theme_dark_onSecondary = Color(0xFF452B00)
val md_theme_dark_secondaryContainer = Color(0xFF624000)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDDB2)
val md_theme_dark_tertiary = Color(0xFFFFB783)
val md_theme_dark_onTertiary = Color(0xFF4F2500)
val md_theme_dark_tertiaryContainer = Color(0xFF703700)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDCC5)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF410005)
val md_theme_dark_onBackground = Color(0xFFFFDAD7)
val md_theme_dark_surface = Color(0xFF410005)
val md_theme_dark_onSurface = Color(0xFFFFDAD7)
val md_theme_dark_surfaceVariant = Color(0xFF4D4639)
val md_theme_dark_onSurfaceVariant = Color(0xFFD0C5B4)
val md_theme_dark_outline = Color(0xFF999080)
val md_theme_dark_inverseOnSurface = Color(0xFF410005)
val md_theme_dark_inverseSurface = Color(0xFFFFDAD7)
val md_theme_dark_inversePrimary = Color(0xFF775A00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFEFC048)
val md_theme_dark_outlineVariant = Color(0xFF4D4639)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFFFD15D)
